### ISSUE TITLE
Compilation failure: relocation R_X86_64_PC32 against symbol ... can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by maximbaz** [wireapp/libsodium-neon#15] opened 2017-06-20 10:16 UTC
Steps:

```
cd wire-desktop
npm install
cd electron
npm run rebuild-neon
```

Error:

```
note: /usr/bin/ld: /tmp/rustc.ZbjniGJ7D9Ug/librust_sodium_sys-24ee5a8b5f6825c1.rlib(libsodium_la-aead_chacha20poly1305.o): relocation R_X86_64_PC32 against symbol `cr
ypto_aead_chacha20poly1305_encrypt_detached' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status
```

Without knowing any details, seems like I need to pass `-fPIC` as a flag to compiler. Googling discovered this [suggestion](https://stackoverflow.com/a/21224447) as well. But how to achieve it, so that the command `npm run rebuild-neon` recognizes it?

System: 

```
ArchLinux x86_64, 4.11.5-1-ARCH.
rustc 1.17.0
```

More logs:

```
   ...
   Compiling rust_sodium-sys v0.3.1
   Compiling rust_sodium v0.3.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/home/maximbaz/private/wire-desktop/electron/node_mod
ules/libsodium-neon/native/target/release/deps/libsodium_neon.0.o" "-o" "/home/maximbaz/private/wire-desktop/el   Compiling rust_sodium-sys v0.3.1
   Compiling rust_sodium v0.3.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/home/maximbaz/private/wire-desktop/electron/node_mod
ules/libsodium-neon/native/target/release/deps/libsodium_neon.0.o" "-o" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-neon/native/target/release/de
ps/liblibsodium_neon.so" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-neon/native/target/release/deps/libsodium_neon.crate.metadata.o" "-Wl,-O1" "
-nodefaultlibs" "-L" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-neon/native/target/release/deps" "-L" "/home/maximbaz/private/wire-desktop/elect
ron/node_modules/libsodium-neon/native/target/release/build/neon-runtime-6dc2209d53919fa5/out" "-L" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-n
eon/native/target/release/build/rust_sodium-sys-9aaf94579de3021f/out/installed/lib" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic"
"-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libneon-aa33400805c59121.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libneon_runtime-86c0
35e58429aef7.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/librust_sodium-3e32b33179c2dc12.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-arc
hive" "/tmp/rustc.ZbjniGJ7D9Ug/libserde-a75d3dcd7ae743de.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libcslice-44233e5f10d88f3a.rlib" "-
Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/librust_sodium_sys-24ee5a8b5f6825c1.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc
.ZbjniGJ7D9Ug/librand-edb078ba7b4b5548.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liblibc-f034dc3c45115c2d.rlib" "-Wl,--no-whole-archiv
e" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liblazy_static-d9471cc515b33152.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libunwrap-
03dd0d4caab6729d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libstd-59ddb13a3f650112.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive
" "/tmp/rustc.ZbjniGJ7D9Ug/libpanic_unwind-767b332f5908b01d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libunwind-f398b0d5b9a21c21.rlib"
 "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/librand-6b4d3f27209030d8.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ
7D9Ug/libcollections-3af8bfb25c05686b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liballoc-f1fb18790492c3aa.rlib" "-Wl,--no-whole-archiv
e" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liballoc_system-7bec18d2ace290c0.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liblibc-c
a857c642bda864a.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libstd_unicode-77fac022534befb6.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-
archive" "/tmp/rustc.ZbjniGJ7D9Ug/libcore-9d5fb400d5bdba42.rlib" "-Wl,--no-whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libcompiler_builtins-9e459e24d06424e8.rlib" "-l" "util"
 "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-shared"
  = note: /usr/bin/ld: /tmp/rustc.ZbjniGJ7D9Ug/librust_sodium_sys-24ee5a8b5f6825c1.rlib(libsodium_la-aead_chacha20poly1305.o): relocation R_X86_64_PC32 against symbol `cr
ypto_aead_chacha20poly1305_encrypt_detached' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status
error: aborting due to previous error
error: Could not compile `libsodium-neon`.
To learn more, run the command again with --verbose.
neon ERR! cargo build failedectron/node_modules/libsodium-neon/native/target/release/de
ps/liblibsodium_neon.so" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-neon/native/target/release/deps/libsodium_neon.crate.metadata.o" "-Wl,-O1" "
-nodefaultlibs" "-L" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-neon/native/target/release/deps" "-L" "/home/maximbaz/private/wire-desktop/elect
ron/node_modules/libsodium-neon/native/target/release/build/neon-runtime-6dc2209d53919fa5/out" "-L" "/home/maximbaz/private/wire-desktop/electron/node_modules/libsodium-n
eon/native/target/release/build/rust_sodium-sys-9aaf94579de3021f/out/installed/lib" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic"
"-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libneon-aa33400805c59121.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libneon_runtime-86c0
35e58429aef7.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/librust_sodium-3e32b33179c2dc12.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-arc
hive" "/tmp/rustc.ZbjniGJ7D9Ug/libserde-a75d3dcd7ae743de.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libcslice-44233e5f10d88f3a.rlib" "-
Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/librust_sodium_sys-24ee5a8b5f6825c1.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc
.ZbjniGJ7D9Ug/librand-edb078ba7b4b5548.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liblibc-f034dc3c45115c2d.rlib" "-Wl,--no-whole-archiv
e" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liblazy_static-d9471cc515b33152.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libunwrap-
03dd0d4caab6729d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libstd-59ddb13a3f650112.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive
" "/tmp/rustc.ZbjniGJ7D9Ug/libpanic_unwind-767b332f5908b01d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libunwind-f398b0d5b9a21c21.rlib"
 "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/librand-6b4d3f27209030d8.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ
7D9Ug/libcollections-3af8bfb25c05686b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liballoc-f1fb18790492c3aa.rlib" "-Wl,--no-whole-archiv
e" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liballoc_system-7bec18d2ace290c0.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/liblibc-c
a857c642bda864a.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libstd_unicode-77fac022534befb6.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-
archive" "/tmp/rustc.ZbjniGJ7D9Ug/libcore-9d5fb400d5bdba42.rlib" "-Wl,--no-whole-archive" "/tmp/rustc.ZbjniGJ7D9Ug/libcompiler_builtins-9e459e24d06424e8.rlib" "-l" "util"
 "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-shared"
  = note: /usr/bin/ld: /tmp/rustc.ZbjniGJ7D9Ug/librust_sodium_sys-24ee5a8b5f6825c1.rlib(libsodium_la-aead_chacha20poly1305.o): relocation R_X86_64_PC32 against symbol `cr
ypto_aead_chacha20poly1305_encrypt_detached' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status
error: aborting due to previous error
error: Could not compile `libsodium-neon`.
To learn more, run the command again with --verbose.
neon ERR! cargo build failed
```

**Comment by ffflorian** [comment] 2017-06-20 10:23
Hi @maximbaz, this is related to https://github.com/maidsafe/rust_sodium/commit/0e9bbdbf445924dc35d3a8ce6ce747d7e8c1c071#commitcomment-21984958 and https://github.com/jedisct1/libsodium/issues/292 and should've been fixed with https://github.com/maidsafe/rust_sodium/pull/34.

Which Rust version do you use?

**Comment by maximbaz** [comment] 2017-06-20 10:27
```
❯  rustc -V
rustc 1.17.0
```

Also I see `Compiling rust_sodium v0.3.0` in the logs, and this version was released 10 days after https://github.com/maidsafe/rust_sodium/pull/34 was merged 🤔

**Comment by ffflorian** [comment] 2017-06-20 10:28
> Also I see Compiling rust_sodium v0.3.0 in the logs, and this version was released 10 days after maidsafe/rust_sodium#34 was merged :thinking:

Exactly. :thinking:

**Comment by maximbaz** [comment] 2017-06-20 19:51
Fix: https://github.com/maidsafe/rust_sodium/pull/40

**Comment by ConorIA** [comment] 2017-06-20 20:44
Repeating your steps, I am _not_ seeing any error.

**Comment by maximbaz** [comment] 2017-06-20 20:46
You probably have `lsb_release` binary, I didn't have it. Currently the installation depends on successfully getting output from `$ lsb_release -irs`.

**Comment by ffflorian** [comment] 2017-06-27 09:00
Since this bug is not caused by `libsodium-neon`, I'll close this issue for now and we'll wait for maidsafe/rust_sodium#40. :)

**Comment by maximbaz** [comment] 2017-07-12 10:06
@ffflorian time to reopen this issue? installing `lsb_release` is not a workaround anymore since https://github.com/maidsafe/rust_sodium/pull/41 is merged, and by the way your builds on Ubuntu will begin to fail again. 

Will you consider setting `RUST_SODIUM_DISABLE_PIE` from within this project itself?

**Comment by ffflorian** [comment] 2017-07-12 10:16
Hi @maximbaz, yes, this is now an issue again. We will decide internally if we set the env variable.

**Comment by aQubesUser** [comment] 2017-07-13 21:26
Seeing this on Qubes 3.2, fedora23 vm. wire-desktop does not build

**Comment by aQubesUser** [comment] 2017-07-14 01:32
Editing `electron/node_modules/libsodium-neon/native/Cargo.toml` for `rust_sodium 0.40` and setting `export RUST_SODIUM_DISABLE_PIE=1` allows me to compile latest `wire-desktop`

**Comment by hex0gen** [comment] 2017-07-15 17:35
aQubesUser, your advice was helpful on ArchLinux. Thanks.

**Comment by aQubesUser** [comment] 2017-07-15 17:58
```
==== JS stack trace =========================================

Security context: 0x3f16864e2259 <String[20]: https://app.wire.com>
    1: /* anonymous */ [https://app.wire.com/min/wire-vendor.min.js?2017-07-06-15-48-prod:7] [pc=0x8cd868b0d7d](this=0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>#0#)
    2: arguments adaptor frame: 1->0
    4: /* anonymous */ [https://app.wire.com/min/wire-vendor.min.js?2017-07-06-15-48-prod:7] [bytecode=0x1b3837793d31 offset=23](this=0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>#0#)
    5: arguments adaptor frame: 1->0

==== Details ================================================

[1]: /* anonymous */ [https://app.wire.com/min/wire-vendor.min.js?2017-07-06-15-48-prod:7] [pc=0x8cd868b0d7d](this=0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>#0#) {
  // heap-allocated locals
  var c = 0x2fe6d23d4711 <an IDBCursorWithValue with map 0x3c66c3ffbd59>#1#
  var f = 0x2fe6d23d4789 <JS Function f (SharedFunctionInfo 0x1b3837793f39)>#2#
  // expression stack (top to bottom)
  [10] : 0x2fe6d23d4711 <an IDBCursorWithValue with map 0x3c66c3ffbd59>#1#
  [09] : 12434
  [08] : 0x16e3a4e02311 <undefined>
  [07] : 0x16e3a4e02311 <undefined>
  [06] : 0x2fe6d23d2571 <JS Object>#3#
  [05] : 0x1b3837794c31 <FunctionTemplateInfo>#4#
  [04] : 0x2fe6d23d46d1 <FixedArray[6]>#5#
  [03] : 0x16e3a4e02311 <undefined>
  [02] : 0x2fe6d23d4711 <an IDBCursorWithValue with map 0x3c66c3ffbd59>#1#
  [01] : 0x16e3a4e02311 <undefined>
  [00] : 0x1b05424e9071 <JS Function (SharedFunctionInfo 0x1d1d7dceb11)>#6#
--------- s o u r c e   c o d e ---------
function (){var c=a.result;if(c){var f=function(){c.continue()};b(c,function(a){f=a},d,e)&&h(c.value,c,function(a){f=a}),f()}else d()}
-----------------------------------------
}

[2]: arguments adaptor frame: 1->0 {
  // actual arguments
  [00] : 0x2fe6d23d4671 <an Event with map 0x3c66c3f93ce9>#7#  // not passed to callee
}

[4]: /* anonymous */ [https://app.wire.com/min/wire-vendor.min.js?2017-07-06-15-48-prod:7] [bytecode=0x1b3837793d31 offset=23](this=0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>#0#) {
  // stack-allocated locals
  var arguments = 0x2fe6d23d46b1 <an Arguments with map 0x1b35baa88df1>#8#
  // expression stack (top to bottom)
  [06] : 0x2fe6d23d46b1 <an Arguments with map 0x1b35baa88df1>#8#
  [05] : 0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>#0#
  [04] : 0x1b05424e9249 <JS Function (SharedFunctionInfo 0x23eefb9704e1)>#9#
  [03] : 0x3f1686499ed1 <JS Function apply (SharedFunctionInfo 0x16e3a4e3cac9)>#10#
  [02] : 0x1b05424e9291 <FixedArray[6]>#11#
  [01] : 0x16e3a4e02311 <undefined>
--------- s o u r c e   c o d e ---------
function (){try{a.apply(this,arguments)}catch(a){b(a)}}
-----------------------------------------
}

[5]: arguments adaptor frame: 1->0 {
  // actual arguments
  [00] : 0x2fe6d23d4671 <an Event with map 0x3c66c3f93ce9>#7#  // not passed to callee
}

==== Key         ============================================

 #0# 0x1b05424e8f09: 0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>
 #1# 0x2fe6d23d4711: 0x2fe6d23d4711 <an IDBCursorWithValue with map 0x3c66c3ffbd59>
 #2# 0x2fe6d23d4789: 0x2fe6d23d4789 <JS Function f (SharedFunctionInfo 0x1b3837793f39)>
 #3# 0x2fe6d23d2571: 0x2fe6d23d2571 <JS Object>
 #4# 0x1b3837794c31: 0x1b3837794c31 <FunctionTemplateInfo>
 #5# 0x2fe6d23d46d1: 0x2fe6d23d46d1 <FixedArray[6]>
                 0: 0x1b05424e9249 <JS Function (SharedFunctionInfo 0x23eefb9704e1)>#9#
                 1: 0x1b05424e8f79 <FixedArray[11]>#12#
                 3: 0x3f1686495c29 <FixedArray[242]>#13#
                 4: 0x2fe6d23d4711 <an IDBCursorWithValue with map 0x3c66c3ffbd59>#1#
                 5: 0x2fe6d23d4789 <JS Function f (SharedFunctionInfo 0x1b3837793f39)>#2#
 #6# 0x1b05424e9071: 0x1b05424e9071 <JS Function (SharedFunctionInfo 0x1d1d7dceb11)>
 #7# 0x2fe6d23d4671: 0x2fe6d23d4671 <an Event with map 0x3c66c3f93ce9>
 #8# 0x2fe6d23d46b1: 0x2fe6d23d46b1 <an Arguments with map 0x1b35baa88df1>
            length: 1
 #9# 0x1b05424e9249: 0x1b05424e9249 <JS Function (SharedFunctionInfo 0x23eefb9704e1)>
 #10# 0x3f1686499ed1: 0x3f1686499ed1 <JS Function apply (SharedFunctionInfo 0x16e3a4e3cac9)>
 #11# 0x1b05424e9291: 0x1b05424e9291 <FixedArray[6]>
                 0: 0x1fff71861131 <JS Function m (SharedFunctionInfo 0x27eb73912ac9)>#14#
                 1: 0x1fff7180c429 <FixedArray[123]>#15#
                 3: 0x3f1686495c29 <FixedArray[242]>#13#
                 4: 0x1b05424e82c1 <JS BoundFunction (BoundTargetFunction 0x1fff718615f9)>#16#
                 5: 0x1b05424e9249 <JS Function (SharedFunctionInfo 0x23eefb9704e1)>#9#
 #12# 0x1b05424e8f79: 0x1b05424e8f79 <FixedArray[11]>
                 0: 0x31b20ef30b09 <JS Function ca (SharedFunctionInfo 0x29f99576a549)>#17#
                 1: 0x31b20ef12411 <FixedArray[60]>#18#
                 3: 0x3f1686495c29 <FixedArray[242]>#13#
                 4: 0x1fff71861251 <JS Function x (SharedFunctionInfo 0x27eb73913361)>#19#
                 5: 0x1b05424e82c1 <JS BoundFunction (BoundTargetFunction 0x1fff718615f9)>#16#
                 6: 0x1b05424e8d79 <JS Function (SharedFunctionInfo 0xd8a1578849)>#20#
                 7: 0x1b05424e8d31 <JS Function (SharedFunctionInfo 0xd8a15798b1)>#21#
                 8: 0x1b05424e8e59 <JS Function (SharedFunctionInfo 0x23eefb96fb59)>#22#
                 9: 0x1b05424e8f09 <an IDBRequest with map 0x3c66c3fdfe21>#0#
                  ...
 #13# 0x3f1686495c29: 0x3f1686495c29 <FixedArray[242]>
                 0: 0x3f16864963c9 <JS Function (SharedFunctionInfo 0x16e3a4e07f49)>#23#
                 1: 0
                 2: 0x3f16864bb2a1 <a Window with map 0x1b35baa8b521>#24#
                 3: 0x3f1686495c29 <FixedArray[242]>#13#
                 4: 0x1da80a1a4b39 <JS Global Object>#25#
                 5: 0x1da80a1bda41 <FixedArray[33]>#26#
                 6: 0x1b35baa87e79 <Map(FAST_HOLEY_ELEMENTS)>#27#
                 7: 0x16e3a4e023b1 <true>
                 8: 0x3f16864a3d29 <JS Function ArrayBuffer (SharedFunctionInfo 0x16e3a4e491b1)>#28#
                 9: 0x1b35baa867c9 <Map(FAST_HOLEY_SMI_ELEMENTS)>#29#
                  ...
 #14# 0x1fff71861131: 0x1fff71861131 <JS Function m (SharedFunctionInfo 0x27eb73912ac9)>
 #15# 0x1fff7180c429: 0x1fff7180c429 <FixedArray[123]>
                 0: 0x1fff71860f81 <JS Function (SharedFunctionInfo 0x3c410a5522e9)>#30#
                 1: 0x3f1686495c29 <FixedArray[242]>#13#
                 3: 0x3f1686495c29 <FixedArray[242]>#13#
                 4: 0x1eb11539c1d1 <JS Function a (SharedFunctionInfo 0x27eb73912169)>#31#
                 5: 0x1eb11539c2a9 <JS Function b (SharedFunctionInfo 0x27eb73912231)>#32#
                 6: 0x1eb115398199 <JS Function c (SharedFunctionInfo 0x27eb739122f9)>#33#
                 7: 0x1fff71860fc9 <JS Function d (SharedFunctionInfo 0x27eb739123c1)>#34#
                 8: 0x1eb11539a621 <JS Function e (SharedFunctionInfo 0x27eb73912489)>#35#
                 9: 0x1fff71861011 <JS Function f (SharedFunctionInfo 0x27eb73912551)>#36#
                  ...
 #16# 0x1b05424e82c1: 0x1b05424e82c1 <JS BoundFunction (BoundTargetFunction 0x1fff718615f9)>
 #17# 0x31b20ef30b09: 0x31b20ef30b09 <JS Function ca (SharedFunctionInfo 0x29f99576a549)>
 #18# 0x31b20ef12411: 0x31b20ef12411 <FixedArray[60]>
                 0: 0x1eb115398f09 <JS Function ka (SharedFunctionInfo 0x2cfe8f6cfab9)>#37#
                 1: 0x1fff7180c429 <FixedArray[123]>#15#
                 3: 0x3f1686495c29 <FixedArray[242]>#13#
                 4: 0x31b20ef16239 <String[62]: wire@production@c3e1d906-027c-4808-884d-0080ec566703@permanent>
                 5: 0x31b20ef1b7b9 <JS Function q (SharedFunctionInfo 0x29f995769419)>#38#
                 6: 0x31b20ef308c9 <JS Function z (SharedFunctionInfo 0x29f9957694e1)>#39#
                 7: 0x31b20ef30911 <JS Function D (SharedFunctionInfo 0x29f9957695a9)>#40#
                 8: 0x31b20ef30959 <JS Function F (SharedFunctionInfo 0x29f995769671)>#41#
                 9: 0x31b20ef309a1 <JS Function H (SharedFunctionInfo 0x29f995769739)>#42#
                  ...
 #19# 0x1fff71861251: 0x1fff71861251 <JS Function x (SharedFunctionInfo 0x27eb73913361)>
 #20# 0x1b05424e8d79: 0x1b05424e8d79 <JS Function (SharedFunctionInfo 0xd8a1578849)>
 #21# 0x1b05424e8d31: 0x1b05424e8d31 <JS Function (SharedFunctionInfo 0xd8a15798b1)>
 #22# 0x1b05424e8e59: 0x1b05424e8e59 <JS Function (SharedFunctionInfo 0x23eefb96fb59)>
 #23# 0x3f16864963c9: 0x3f16864963c9 <JS Function (SharedFunctionInfo 0x16e3a4e07f49)>
 #24# 0x3f16864bb2a1: 0x3f16864bb2a1 <a Window with map 0x1b35baa8b521>
 #25# 0x1da80a1a4b39: 0x1da80a1a4b39 <JS Global Object>
 #26# 0x1da80a1bda41: 0x1da80a1bda41 <FixedArray[33]>
                 0: 0x1da80a1bdca9 <String[42]: 1,1,{"isDefault":true,"frameId":"24829.1"}>
                 1: 12434
                 2: 8725
                 3: 0x16e3a4e02311 <undefined>
                 4: 0x16e3a4e02311 <undefined>
                 5: 0x16e3a4e02311 <undefined>
                 6: 0x16e3a4e02311 <undefined>
                 7: 0x16e3a4e02311 <undefined>
                 8: 0x16e3a4e02311 <undefined>
                 9: 0x16e3a4e02311 <undefined>
                  ...
 #27# 0x1b35baa87e79: 0x1b35baa87e79 <Map(FAST_HOLEY_ELEMENTS)>
 #28# 0x3f16864a3d29: 0x3f16864a3d29 <JS Function ArrayBuffer (SharedFunctionInfo 0x16e3a4e491b1)>
 #29# 0x1b35baa867c9: 0x1b35baa867c9 <Map(FAST_HOLEY_SMI_ELEMENTS)>
 #30# 0x1fff71860f81: 0x1fff71860f81 <JS Function (SharedFunctionInfo 0x3c410a5522e9)>
 #31# 0x1eb11539c1d1: 0x1eb11539c1d1 <JS Function a (SharedFunctionInfo 0x27eb73912169)>
 #32# 0x1eb11539c2a9: 0x1eb11539c2a9 <JS Function b (SharedFunctionInfo 0x27eb73912231)>
 #33# 0x1eb115398199: 0x1eb115398199 <JS Function c (SharedFunctionInfo 0x27eb739122f9)>
 #34# 0x1fff71860fc9: 0x1fff71860fc9 <JS Function d (SharedFunctionInfo 0x27eb739123c1)>
 #35# 0x1eb11539a621: 0x1eb11539a621 <JS Function e (SharedFunctionInfo 0x27eb73912489)>
 #36# 0x1fff71861011: 0x1fff71861011 <JS Function f (SharedFunctionInfo 0x27eb73912551)>
 #37# 0x1eb115398f09: 0x1eb115398f09 <JS Function ka (SharedFunctionInfo 0x2cfe8f6cfab9)>
            maxKey: 0x1fff71862091 <JS Array[1]>#43#
            addons: 0x1fff71862149 <JS Array[0]>#44#
       connections: 0x1fff718620b1 <JS Array[1]>#45#
          errnames: 0x1fff71862169 <an Object with map 0x1b35baad6689>#46#
      dependencies: 0x1fff71862181 <an Object with map 0x1b35baac72d1>#47#
            semVer: 0x2cfe8f6d3339 <String[5]: 1.5.1>
           version: 0x1fff718621a9 <MutableNumber: 1.0501>#48#
 #38# 0x31b20ef1b7b9: 0x31b20ef1b7b9 <JS Function q (SharedFunctionInfo 0x29f995769419)>
 #39# 0x31b20ef308c9: 0x31b20ef308c9 <JS Function z (SharedFunctionInfo 0x29f9957694e1)>
 #40# 0x31b20ef30911: 0x31b20ef30911 <JS Function D (SharedFunctionInfo 0x29f9957695a9)>
 #41# 0x31b20ef30959: 0x31b20ef30959 <JS Function F (SharedFunctionInfo 0x29f995769671)>
 #42# 0x31b20ef309a1: 0x31b20ef309a1 <JS Function H (SharedFunctionInfo 0x29f995769739)>
 #43# 0x1fff71862091: 0x1fff71862091 <JS Array[1]>
                 0: 0x2224e3eadfb9 <JS Array[0]>#49#
 #44# 0x1fff71862149: 0x1fff71862149 <JS Array[0]>
 #45# 0x1fff718620b1: 0x1fff718620b1 <JS Array[1]>
                 0: 0x31b20ef18a61 <a ka with map 0x2d3045028b61>#50#
 #46# 0x1fff71862169: 0x1fff71862169 <an Object with map 0x1b35baad6689>
 #47# 0x1fff71862181: 0x1fff71862181 <an Object with map 0x1b35baac72d1>
         indexedDB: 0x1eb11539c541 <an IDBFactory with map 0x1b35baac6461>#51#
       IDBKeyRange: 0xdaf264571c9 <JS Function IDBKeyRange (SharedFunctionInfo 0xdaf26457119)>#52#
      localStorage: 0x1eb115398ba9 <a Storage with map 0x1b35baadda09>#53#
 #48# 0x1fff718621a9: 0x1fff718621a9 <MutableNumber: 1.0501>
 #49# 0x2224e3eadfb9: 0x2224e3eadfb9 <JS Array[0]>
 #50# 0x31b20ef18a61: 0x31b20ef18a61 <a ka with map 0x2d3045028b61>
 #51# 0x1eb11539c541: 0x1eb11539c541 <an IDBFactory with map 0x1b35baac6461>
 #52# 0xdaf264571c9: 0xdaf264571c9 <JS Function IDBKeyRange (SharedFunctionInfo 0xdaf26457119)>
 #53# 0x1eb115398ba9: 0x1eb115398ba9 <a Storage with map 0x1b35baadda09>
=====================
```
on wire-desktop d08a6f5404482828adaec1fa54893c470864caca

**Comment by maximbaz** [comment] 2017-07-15 18:09
I had that same experience too, release 2.15.2747 was the last working version, and upgrading to every version after that resulted in black screen.

However, to experiment I decided to kill all history, logged out, deleted `~/.Wire`, then installed the latest release 2.15.2750, logged in and it works, no black screen. I think there's some incompatibility with upgrading. This is not a viable workaround though. FYI @ffflorian

**Comment by aQubesUser** [comment] 2017-07-16 15:42
Good to know. Thank you @maximbaz

**Comment by lanodan** [comment] 2017-08-30 15:03
(No idea if this should go to libsodium-neon or not)
If lsb_release is what is needed there SHOULD (if not MUST) at least be a error/warning/… message on that.

**Comment by ConorIA** [comment] 2017-11-02 12:58
Hey all, I'm hitting this on the copr builds (e.g. [Fedora 27](https://copr-be.cloud.fedoraproject.org/results/conoria/wire-desktop/fedora-27-x86_64/00656996-wire-desktop/builder-live.log)). Is `lsb-release` still the "fix", or should I try to export `RUST_SODIUM_DISABLE_PIE`, or should I just wait for #18?

**Comment by maximbaz** [comment] 2017-11-02 13:04
`lsb-release` should still be the correct workaround to use until the `rust_sodium` is updated to `0.4.0`+:

https://github.com/wireapp/libsodium-neon/blob/6f6efbc2b48319dddc41917b76ccc0fa207130d0/native/Cargo.toml#L18

`RUST_SODIUM_DISABLE_PIE` has no effect in `0.3.0`.

**Closed** 2018-01-15 09:59 UTC

**Comment by ffflorian** [comment] 2018-01-15 10:43
Can you all try building it with [v2.1.2](https://github.com/wireapp/libsodium-neon/releases/tag/v2.1.2)?

Just run `yarn build` or `npm run build` after cloning the project.

**Comment by maximbaz** [comment] 2018-01-15 19:58
It compiles successfully, thank you 👍 
`lsb-release` can be removed since the next Wire release.
